In [4]:
import pandas as pd
pd.read_csv("y_test.csv")

    Unnamed: 0  Label
0           19      0
1           42      0
2          153      1
3           78      0
4          145      1
5           15      0
6           24      0
7           68      0
8          113      0
9          118      0
10          93      0
11         159      1
12          69      0
13         142      1
14          45      0
15          16      0
16          51      0
17         125      1
18          96      0
19          56      0
20          97      0
21         120      1
22         143      1
23          30      0
24           9      0
25         172      1
26          60      0
27          18      0
28         148      1
29         173      1
30         109      0
31          55      0
32         140      1
33         126      1
34          66      0
35          29      0
36         117      0
37          65      0
38          67      0
39          31      0
40          12      0
41          41      0
42         124      1
43         100      0
44         161      1
45         132      1
46          90      0
47          38      0
48         169      1
49         115      0
50         171      1
51         156      1
52           2      0
53         176      1